### ISSUE TITLE
Issue on Installing project

### ISSUE THREAD

**Issue by Aju100** [officialnosk/officialnosk.github.io#4]
@MegaMind98 @theonlyNischal  Hello Brothers, I wanted to set up this same open-source project in my local machine. I followed above README instructions too but I am not able to do it. Also, I tried to update all of my gems and sudo apt-get update too. How can I set up this project on my local machine ???
![Screenshot from 2019-09-19 05-16-33](https://user-images.githubusercontent.com/29862610/65194936-b781c800-da9c-11e9-8524-f01cee2df049.png)
![Screenshot from 2019-09-19 05-16-40](https://user-images.githubusercontent.com/29862610/65194947-be103f80-da9c-11e9-846c-0b4b0957baa1.png)

**Comment by MegaMind98** [comment]
Hello Aju!

Are you having trouble installing Jekyll? Please be more specific about the issue.

In the meantime, you can look for Jekyll installation instructions for Ubuntu [here](https://jekyllrb.com/docs/installation/ubuntu/).

**Comment by Aju100** [comment]
no @MegaMind98 i have already install Jekyll

**Comment by Aju100** [comment]
the problem is one the dependency gem is not installed.

**Comment by MegaMind98** [comment]
Aju, please refer to the issue [here](https://github.com/jekyll/jekyll-help/issues/209). The problem might be because you're missing the 'ruby-dev' package.

**Comment by Aju100** [comment]
I have already done Brother.
`sudo apt-get install ruby-dev` too
The problem is not able to serve the page.
![Screenshot from 2019-09-20 04-46-55](https://user-images.githubusercontent.com/29862610/65287124-b5ce0800-db61-11e9-9fb2-e97453412ff4.png)

**Comment by MegaMind98** [comment]
Just like it says, prepend 'bundle exec' to jekyll serve. 

```sh
bundle exec jekyll serve
```

**Comment by Aju100** [comment]
@MegaMind98  Thanks Dae.
